# Usage:
#   docker compose -f docker-compose.yml -f docker-compose.gpu.yml up --build

services:

  api:
    build:
      dockerfile: Dockerfile.gpu
    environment:
      - USE_GPU=true

  worker:
    build:
      dockerfile: Dockerfile.gpu
    environment:
      - USE_GPU=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
